 const dediny = [
    "Ružomberok",
    "Hubová",
    "Ivachnová",
    "Kalameny",
    "Komjatná",
    "Likavka",
    "Liptovská Lúžna",
    "Liptovská Osada",
    "Liptovská Štiavnica",
    "Liptovská Teplá",
    " Liptovské Revúce",
    " Liptovské Sliače",
    " Liptovský Michal",
    "Lisková",
    "Ľubochňa",
    "Lúčky",
    "Ludrová",
    " Martinček",
    "Potok",
    "Stankovany",
    "Štiavnička",
    "Švošov",
    "Turík",
    " Valaská Dubová",
  ];

  export default dediny